### PR TITLE
Manage query with full body

### PR DESCRIPTION
**Pull request by mabhub**
This allows to do Elasticsearch [Request Body Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html) with [Source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html) or [sorting](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html).

### CODE REVIEW

**Comment by chuntley** [comment]
Thank you for the contribution, I'll be looking into this tonight!

**Comment by arnorhs** [comment]
@chuntley so, have you looked into it?

**Comment by arnorhs** [comment]
Just wondering about the overall status of this project atm. Whether it is maintained and how stable it is, etc :) thanks!

**Comment by chuntley** [comment]
@arnorhs I actually did look into it that night, but completely forgot to follow up with the merge! I'm not actively using this extension however I do not spot any breaking changes.

**Pull request merged**
